### GET ALL ITEMS
GET http://localhost:8080/items HTTP/1.1

### GET A PARTICULAR ITEM
GET http://localhost:8080/items/2 HTTP/1.1

### ADD A NEW ITEM
POST http://localhost:8080/items HTTP/1.1
Content-Type: application/json

{
    "name": "New Item One"
}

### UPDATE AN ITEM
PUT http://localhost:8080/items/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Item One"
}

### DELETE AN ITEM
DELETE http://localhost:8080/items/541f2dcc-3a56-4416-b9dc-b7114ea3d1a2 HTTP/1.1
